- name: create custom credential type
  awx.awx.tower_credential_type:
    name: "{{ credential_type }}"
    description: "custom credential for {{ repo }}"
    kind: cloud
    injectors:
      env:
        SECRET1: !unsafe '{{ secret1 }}'
        SECRET2: !unsafe '{{ secret2 }}'
      extra_vars:
        secret1: !unsafe '{{ secret1 }}'
        secret2: !unsafe '{{ secret2 }}'
    inputs:
      fields:
        - id: secret1
          label: secret1
          secret: true
          type: string
        - id: secret2
          label: secret2
          secret: true
          type: string
      required:
        - secret1
        - secret2

- name: create custom credential
  awx.awx.tower_credential:
    state: present
    name: "{{ custom_credential }}"
    description: "custom credential for {{ repo }}"
    organization: "{{ organization }}"
    credential_type: "{{ credential_type }}"
    # we'll populate all of this from vault in the next plays
    inputs:
      secret1: placeholder
      secret2: placeholder
  no_log: true

- name: link the custom credential secret1 to vault
  awx.awx.credential_input_source:
    state: present
    input_field_name: secret1
    target_credential: "{{ custom_credential }}"
    source_credential: "{{ vault_lookup_credential }}"
    metadata:
      secret_path: /secret/{{ custom_secret.name }}
      secret_key: secret1

- name: link the custom credential secret1 to vault
  awx.awx.credential_input_source:
    state: present
    input_field_name: secret2
    target_credential: "{{ custom_credential }}"
    source_credential: "{{ vault_lookup_credential }}"
    metadata:
      secret_path: /secret/{{ custom_secret.name }}
      secret_key: secret2
