- name: create machine credential
  awx.awx.tower_credential:
    state: present
    name: "{{ machine_credential }}"
    description: "machine credential for {{ repo }}"
    organization: "{{ organization }}"
    credential_type: Machine
    # we'll populate all of this from vault in the next plays
    inputs:
      username: "{{ awx_service_account.name }}"
      password: hunter2
      ssh_key_data: "{{ lookup('file', '/dev/null') }}"
      ssh_key_unlock: hunter2
  no_log: true

- name: link the machine credential password to vault
  awx.awx.credential_input_source:
    state: present
    input_field_name: password
    target_credential: "{{ machine_credential }}"
    source_credential: "{{ vault_lookup_credential }}"
    metadata:
      secret_path: /secret/{{ awx_service_account.name }}
      secret_key: password

- name: link the machine credential ssh key to vault
  awx.awx.credential_input_source:
    state: present
    input_field_name: ssh_key_data
    target_credential: "{{ machine_credential }}"
    source_credential: "{{ vault_lookup_credential }}"
    metadata:
      secret_path: /secret/{{ awx_service_account.name }}
      secret_key: ssh_private_key

- name: link the machine credential ssh key passphrase to vault
  awx.awx.credential_input_source:
    state: present
    input_field_name: ssh_key_unlock
    target_credential: "{{ machine_credential }}"
    source_credential: "{{ vault_lookup_credential }}"
    metadata:
      secret_path: /secret/{{ awx_service_account.name }}
      secret_key: ssh_passphrase
