---
- name: debug
  hosts: all
  gather_facts: true
  tasks:
    - name: debug
      ansible.builtin.debug:
        msg: |
          environment:
            $SECRET1: {{ lookup('ansible.builtin.env', 'SECRET1' }}
            $SECRET2: {{ lookup('ansible.builtin.env', 'SECRET2' }}
          variables:
            secret1: {{ secret1 }}
            secret2: {{ secret2 }}
