all:
  vars:
    awx_service_account:
      name: awx
      group: awx
      comment: AWX Service Account
      create_home: true
      home: /Users/awx
      shell: /bin/bash
      password_lock: false
      password: "{{ lookup('ansible.builtin.env', 'AWX_SA_PASSWORD') }}"
      update_password: always
      ssh_private_key: "{{ lookup('ansible.builtin.env', 'AWX_SA_SSH_PRIVATE_KEY') }}"
      ssh_public_key: "{{ lookup('ansible.builtin.env', 'AWX_SA_SSH_PUBLIC_KEY') }}"
      ssh_passphrase: "{{ lookup('ansible.builtin.env', 'AWX_SA_SSH_PASSPHRASE') }}"
    custom_secret:
      name: awx-hashi-vault
      secret1: hunter2
      secret2: s3kr3t1
    vault:
      api_version: v1
      cacert: ""
      default_auth_path: approle
      namespace: ""
      role_id: "{{ lookup('ansible.builtin.env', 'VAULT_ROLE_ID') }}"
      secret_id: "{{ lookup('ansible.builtin.env', 'VAULT_SECRET_ID') }}"
      url: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"
  hosts:
    localhost:
      connection: local
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
    honeycrisp:
      ansible_host: 192.168.1.105
      ansible_user: awx
      connection: ssh
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
  children:
    awx_managed:
      hosts:
        honeycrisp:
