all:
  vars:
    vault:
      api_version: v1
      cacert: ""
      default_auth_path: approle
      namespace: ""
      role_id: "{{ lookup('ansible.builtin.env', 'VAULT_ROLE_ID') }}"
      secret_id: "{{ lookup('ansible.builtin.env', 'VAULT_SECRET_ID') }}"
      url: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"
  hosts:
    localhost:
      connection: local
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
    jonagold:
      ansible_host: 192.168.1.105
      ansible_user: mark
      connection: ssh
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
  children:
    awx_managed:
      hosts:
        jonagold:
