all:
  vars:
    awx_service_account:
      name: awx
      group: awx
      comment: AWX Service Account
      create_home: true
      home: /Users/awx
      password_lock: false
      shell: /bin/bash
      password: "{{ lookup('ansible.builtin.env', 'AWX_SA_PASSWORD') }}"
      ssh_private_key_b64: "{{ lookup('ansible.builtin.env', 'AWX_SA_SSH_PRIVATE_KEY_B64') }}"
      ssh_public_key_b64: "{{ lookup('ansible.builtin.env', 'AWX_SA_SSH_PUBLIC_KEY_B64') }}"
      ssh_key_passphrase: "{{ lookup('ansible.builtin.env', 'AWX_SA_SSH_PASSPHRASE') }}"
    vault:
      api_version: v1
      cacert: ""
      default_auth_path: approle
      namespace: ""
      role_id: "{{ lookup('ansible.builtin.env', 'VAULT_ROLE_ID') }}"
      secret_id: "{{ lookup('ansible.builtin.env', 'VAULT_SECRET_ID') }}"
      url: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"
  hosts:
    localhost:
      connection: local
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
    jonagold:
      ansible_host: 192.168.1.105
      ansible_user: mark
      connection: ssh
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
  children:
    awx_managed:
      hosts:
        jonagold:
