---
- name: prep-infra
  hosts: awx_managed
  connection: ssh
  gather_facts: false
  become: false
  tasks:
    - name: include prep-infra role
      ansible.builtin.include_role:
        name: prep-infra
