---
- name: prep-vault
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: include prep-vault role
      ansible.builtin.include_role:
        name: prep-vault
---
- name: prep-infra
  hosts: awx_managed
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: include prep-infra role
      ansible.builtin.include_role:
        name: prep-infra
---
- name: prep-awx
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: include prep-awx role
      ansible.builtin.include_role:
        name: prep-awx
