---
# defaults file for prep-infra

awx_service_account:
  name: awx
  group: awx
  comment: AWX Service Account
  create_home: true
  home: /Users/awx
  shell: /bin/bash
  password_lock: true
  password: hunter2
  update_password: always
